[package]
name = "vault"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
lazy_static =  { version = "1.4.0"}
rusqlite = { version = "0.27.0", features = ["bundled-sqlcipher-vendored-openssl","backup","vtab","url" ,"blob","chrono","serde_json","hooks"] }
deadpool = "0.9.3"
thiserror = "1.0.30"
serde="1.0.135"
serde_json="1.0.79"
rust-argon2 = "1.0"
#argon2 = "0.4"
rand_core = { version = "0.6", features = ["std"] }
blake3 = "1.3.1"
hex = "0.4.3"
deadpool-sync = "0.1.0"
object-pool = "0.5.4"

