[package]
name = "vault"
version = "0.1.0"
edition = "2021"

[dependencies]
#database 
rusqlite = { version = "0.27.0", features = ["bundled-sqlcipher-vendored-openssl","backup","vtab","url" ,"blob","chrono","serde_json","hooks"] }
object-pool = "0.5.4"
# not compatible diesel = { version = "1.4.8", features=["sqlite", "extras", "large-tables", "numeric" ]}

#crypto
rust-argon2 = "1.0"
blake3 = "1.3.1"
hex = "0.4.3"
rand = "0.8.5"
ed25519-dalek = "1.0.1"


#other
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
lazy_static =  { version = "1.4.0"}
qp2p = "0.28.5"
speedy = "0.8.1"