[package]
name = "vault"
version = "0.1.0"
edition = "2021"

[dependencies]
#database 
rusqlite = { version = "0.27.0", features = ["bundled-sqlcipher-vendored-openssl","backup","vtab","url" ,"blob","chrono","serde_json","hooks"] }
object-pool = "0.5.4"

## Crypto
rust-argon2 = "1.0"
blake3 = "1.3.1"
ed25519-dalek = "1.0.1"
rustls = { version = "0.20.2", default-features = false, features = ["quic", "dangerous_configuration"] }
rcgen = "0.9.2"

## Network
quinn = { version = "0.8.0", default-features = false, features = ["tls-rustls", "ring"] }

## Serialisation
serde = { version = "1.0.136", features = ["derive"] }
bincode = "1.3.3"

## Other
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
lazy_static =  { version = "1.4.0"}
hex = "0.4.3"
rand = "0.8.5"

