[package]
name = "discret"
version = "0.1.0"
edition = "2021"

[profile.release-lto]
inherits = "release"
lto = "fat"
codegen-units = 1
strip = true 

[dependencies]
## database 
rusqlite = { version = "0.28.0", features = ["bundled-sqlcipher-vendored-openssl","backup","vtab","url" ,"blob","chrono","serde_json","hooks"] }

## Serialisation
serde = { version = "1.0.152", features = ["derive"] }
bincode = "1.3.3"
serde_json = "1.0.92"
hex = "0.4.3"
base64 = "0.21.0"

## Crypto
rust-argon2 = "1.0.0"
blake3 = "1.3.3"
ed25519-dalek = "1.0.1"
x25519-dalek = "1.2.0"
rustls = { version = "0.20.8", default-features = false, features = ["quic", "dangerous_configuration"] }
rcgen = "0.10.0"
rand = "0.8.5"
#secrecy = "0.8.0"

## Network
quinn = { version = "0.9.3", default-features = false, features = ["tls-rustls", "ring", "runtime-tokio"] }
futures = "0.3.26"
socket2 = "0.4.7"

#Error and tracing
thiserror = "1.0.38"
anyhow = "1.0.69"
tracing = "0.1.34"
tracing-futures = "0.2.5"
tracing-subscriber = "0.3.16"

## Other
tokio = { version = "1.25.0", features = ["full"] }
lazy_static = "1.4.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name    = "bench_main"
harness = false




